require: rubocop-rails

Rails:
  Enabled: true
AllCops:
  SuggestExtensions:
    rubocop-rspec: false
  Exclude:
    - 'vendor/**/*'
    - db/schema.rb
    - db/migrate/*.rb
    - bin/setup
    - bin/update
    - bin/rails
    - bin/rake
    - bin/bundle
    - bin/rails_helper
Metrics/ClassLength:
  Max: 200
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 9
Layout/LineLength:
  Enabled: false
  Max: 120
  Include:
    - 'app/**/*'
  Exclude:
    - 'db/schema.rb'
Layout/BeginEndAlignment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/DuplicateRequire:
  Enabled: false
Lint/DuplicateRescueException:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/HashCompareByIdentity:
  Enabled: false
Lint/IdentityComparison:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/RedundantSafeNavigation:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Lint/UselessTimes:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ClassEqualityComparison:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RedundantSelfAssignment:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Rails/ActiveRecordCallbacksOrder:
  Enabled: false
Rails/AfterCommitOverride:
  Enabled: false
Rails/AttributeDefaultBlockValue:
  Enabled: false
Rails/FindById:
  Enabled: false
Rails/Inquiry:
  Enabled: false
Rails/MailerName:
  Enabled: false
Rails/MatchRoute:
  Enabled: false
Rails/NegateInclude:
  Enabled: false
Rails/Pluck:
  Enabled: false
Rails/PluckInWhere:
  Enabled: false
Rails/RenderInline:
  Enabled: false
Rails/RenderPlainText:
  Enabled: false
Rails/ShortI18n:
  Enabled: false
Rails/SquishedSQLHeredocs:
  Enabled: false
Rails/WhereEquals:
  Enabled: false
Rails/WhereExists:
  Enabled: false
Rails/WhereNot:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: false
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: false
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: false
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: false
Lint/EmptyBlock: # (new in 1.1)
  Enabled: false
Lint/EmptyClass: # (new in 1.3)
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: false
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: false
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: false
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: false
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: false
Style/CollectionCompact: # (new in 1.2)
  Enabled: false
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: false
Style/EndlessMethod: # (new in 1.8)
  Enabled: false
Style/HashExcept: # (new in 1.7)
  Enabled: false
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: false
Style/NilLambda: # (new in 1.3)
  Enabled: false
Style/RedundantArgument: # (new in 1.4)
  Enabled: false
Style/SwapValues: # (new in 1.1)
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Gemspec/DateAssignment: # new in 1.10
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Lint/AmbiguousRange: # new in 1.19
  Enabled: false
Lint/EmptyInPattern: # new in 1.16
  Enabled: false
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: false
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: false
Lint/SymbolConversion: # new in 1.9
  Enabled: false
Lint/TripleQuotes: # new in 1.9
  Enabled: false
Naming/InclusiveLanguage: # new in 1.18
  Enabled: false
Style/HashConversion: # new in 1.10
  Enabled: false
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: false
Style/InPatternThen: # new in 1.16
  Enabled: false
Style/MultilineInPatternThen: # new in 1.16
  Enabled: false
Style/QuotedSymbols: # new in 1.16
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: false
Style/StringChars: # new in 1.12
  Enabled: false
Rails/AddColumnIndex: # new in 2.11
  Enabled: false
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: false
Rails/ExpandedDateRange: # new in 2.11
  Enabled: false
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: false
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: false
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: false
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: false
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: false
Security/IoMethods: # new in 1.22
  Enabled: false
Style/NumberedParameters: # new in 1.22
  Enabled: false
Style/NumberedParametersLimit: # new in 1.22
  Enabled: false
Style/SelectByRegexp: # new in 1.22
  Enabled: false
Rails/RedundantTravelBack: # new in 2.12
  Enabled: false
