default: &default
  api_base_url: <%= ENV['API_BASE_URL'] %>

  # JWT
  jwt_auth_key: <%= ENV['JWT_AUTH_KEY'] %>
  default_admin_user_pass: <%= ENV['DEFAULT_ADMIN_USER_PASS'] %>

  # DATABASE
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_port: <%= ENV['DATABASE_PORT'] %>
  database_user: <%= ENV['DATABASE_USER'] %>
  database_pass: <%= ENV['DATABASE_PASS'] %>
  database_name: <%= ENV['DATABASE_NAME'] %>

development: &development
  <<: *default

test: &test
  <<: *development

production: &production
  <<: *default
